### ISSUE TITLE
Weird behavior of bluestone!!!!

### ISSUE THREAD

**Issue by SevenIsNotNumber** [MultiCraft/MultiCraft_game#1]
First of all redstone block can activate diagonally on vertical axis.(Dont fix). Slime not working no observer... Idea! Bluestone overhaul update. @MoNTE48 ....

**Comment by XREALM-YT** [comment]
Where do I send issues again ?
Believe me I have many bugs 🐜

**Comment by MoNTE48** [comment]
@XREALM-YT you can report it here.

**Comment by XREALM-YT** [comment]
> @XREALM-YT you can report it here.

Yay thx 🙏🏼 time to help out

**Comment by XREALM-YT** [comment]
> @XREALM-YT you can report it here.

Kk

**Comment by XREALM-YT** [comment]
> @XREALM-YT you can report it here.

@MoNTE48 when will skins come out? I also had an idea if we can also customize capes with hearts of lighting or put a panda sticker on them reply if you liked the idea :) also if we can have volcanos in mountains or is that hard

**Comment by Malaska678** [comment]
Skin creator can be good idea

**Comment by XREALM-YT** [comment]
> Skin creator can be good idea

Yes :) also want instead if witches vampires to not copy the other game much

**Comment by githubXREALM** [comment]
> Skin creator can be good idea

I know right

**Comment by MoNTE48** [comment]
So bluestone or skin issues? Are you familiar with the rules of conduct on github?
1 thing for 1 issue. Discussion only on the topic.
This is not contact with developers. This message is about 1 bug or 1 request.

**Comment by githubXREALM** [comment]
> So bluestone or skin issues? Are you familiar with the rules of conduct on github?
> 1 thing for 1 issue. Discussion only on the topic.
> This is not contact with developers. This message is about 1 bug or 1 request.

@MoNTE48 may you tell me the rules?

**Comment by githubXREALM** [comment]
Im gonna go checkout the rules
