### ISSUE TITLE
Floating sand 😯 

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#10]
Idk if it’s a bug but when you place sand or gravel etc. 

#1 PLACE OIL ON THE FLOOR

#2 PLACE GRAVEL OR SAND ON TOP OF THE OIL

#3 WAIT FOR IT TO TAKE OUT

#4 IT WILL FLOAT!

#5 that’s it 😂 

Where can I send you videos of bugs? Some are really weird I can’t explain them well

The magic word “I ❤️ MultiCraft 

And the developers for updating!

**Comment by MoNTE48** [comment]
Well, they'll float until you hit them. Oil is a complete block for a while. Therefore, it is not easy to fix. And in general, is it necessary to fix this?

**Comment by XREALM-YT** [comment]
I think floating sand trick is actually cool :) I don’t think it’s necessary 

I agree ☝️
