### ISSUE TITLE
REMOVING PRO BLOCKS! 🚨 jeeez my brain blew out when I discovered this

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#11]
You can push a pro block away using a piston :/ 

and one question.. are you the Admin of the survival server?

**Comment by MoNTE48** [comment]
Well, that won't change anything. In fact, the protection block does not protect anything. You can push it 100 blocks away, but the area will not change.

**Comment by XREALM-YT** [comment]
O_O ok 👍 
That’s good to know :)
