### ISSUE TITLE
Giant zombie issues

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#12]
Ok my issue with the GAINT ZOMBIES 🧟‍♂️ are they can’t really hit me unless I jump or am at the hight of their waist. And also they kinda teleport when you don’t move.

**Comment by MoNTE48** [comment]
The giant zombies will be removed soon.

**Comment by XREALM-YT** [comment]
Maybe replace it for a baby zombie? 😀 and zombie baby can run quick?

**Comment by XREALM-YT** [comment]
GAINT zombies zombies should be replaced for Baby zombies. Baby zombie should have the GAINT zombies speed and be born after 2 zombies get close to each other or just spawn in the dark

**Comment by XREALM-YT** [comment]
@MoNTE48 when :) pls tell to tell everyone else.... or is it depends?
