### ISSUE TITLE
Rain lags

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#17]
When It rains sometimes I lag a lot :( 
Even If I Disable far viewing rage
It’s not too big of a bug 🐛 but I need to /weather none every 6 minutes Or something to stop it

**Comment by XREALM-YT** [comment]
@MoNTE48 how do I use commands by the way? Like all of them O_O 
Can you give me a list of all the commands there’s some not showing on /help all that i discovered

**Comment by MoNTE48** [comment]
A list of commands is available on request `/help`. There are no other commands.
