### ISSUE TITLE
Skins turns to blank 

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#19]
This dosent usually happen But my skin turn just white when I enter hosted servers and I need to leave and come back to the server to fix it. Fix issue if you want If you don’t want to it ok cuz this dosent usually happen just letting u know :)

**Comment by XREALM-YT** [comment]
@MoNTE48 DAMM I AM SHOWING SO MANY ISSUES I SHOULD SHUT THE FREAK UP AND SAY THEM LATER right I think I’m annoying :/\

**Comment by MoNTE48** [comment]
How often does this happen? Never seen this bug.

**Comment by XREALM-YT** [comment]
> How often does this happen? Never seen this bug. 

1 once a month or something :/ i think its normal cuz when i hit someone they turn white then back .hmmm even when they hold something in hand it turns white

**Comment by XREALM-YT** [comment]
> How often does this happen? Never seen this bug. 

@MoNTE48 speking of the white skin my ears hurt when the ough sound comes when you get hit :| and pls make the sensitivity for phone multicrafters a bit more faster :)
