### ISSUE TITLE
Beds

### ISSUE THREAD

**Issue by ginggingthepharmacist** [MultiCraft/MultiCraft_game#2]
There seems to be a problem with entering beds to sleep.

**Comment by MoNTE48** [comment]
Fixed. Thank you for bug report!

**Comment by XREALM-YT** [comment]
> Fixed. Thank you for bug report!

If you blow up a tnt near armor stand it floats which is funny 😄 wait... you can also duplicate your armor there so.. That’s not funny :/ pls fix

**Comment by XREALM-YT** [comment]
> Fixed. Thank you for bug report!
I ❤️ MultiCraft:)

**Comment by MoNTE48** [comment]
@XREALM-YT, only entity will remain of the armor stand. It will disappear when reload the map. Duplication is not possible.
