### ISSUE TITLE
Sensitivity

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#21]
I cant move my screen fast pls make the game sensitivity faster :)

**Comment by XREALM-YT** [comment]
@MoNTE48 can i join the Multicraft Organization? 😁

**Comment by XREALM-YT** [comment]
@MoNTE48 i can help with some stuff like well.. i have 1.88k multicrafters in the multicraft youtube channel my channel is XREALM i show there how to use stuff in video tutorials but somethings i get mixed up with. I can help design things im good at that :) pls pls pls i want to join the multicraft organization its my dream job too..i can also report bugs everyday with the multicrafters comment on my videos
And report hackers like yourlocalbread in the survival server who robs stuff even with protector block on area and flys without privs...........................................

Pls i know lots of things 🤓 i even started the youtube and facebook multicraft community pls pls pls i want to join help create and draw design stuff like making the sheep cuter

@MoNTE48 pls 😶

**Comment by XREALM-YT** [comment]
@MoNTE48 i looked in the multicraft downloads... DID YOU HIT 10MILLION YET? If you did then. CONGRATS!!!!!!!!!!!!!!!!
pls tell me multicraft made it to 10million :/

**Comment by MoNTE48** [comment]
Please don't spam.  Here we are developing the game engine.  If you want to report a bug, please do so.  Otherwise, you are wasting valuable time from the developers.  This is not a place to leave reviews
