### ISSUE TITLE
Bad banning

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#26]
I type /ban XREALMDDDDDD and it bans me XREALM why is that? :( i also lost my server

**Comment by MoNTE48** [comment]
Well yes, you can block yourself. And there is no way to unlock it. Only create a new world.

**Comment by XREALM-YT** [comment]
> Well yes, you can block yourself. And there is no way to unlock it. Only create a new world.

If i ban someone named Roxnne101 it bans me too :/ i should never ban anyone even if im a admin :|
