### ISSUE TITLE
Tnt activate and pvp

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#27]
Is there a command or option to anable or disable tnt or pvp like damage when you own a hosted server? @MoNTE48

**Comment by MoNTE48** [comment]
Not now, but it will be available in the settings menu. We plan to add this feature by the end of the year.

**Comment by XREALM-YT** [comment]
> Not now, but it will be available in the settings menu. We plan to add this feature by the end of the year. 

yayayayayyayaayaaayaayauay THX FOR THE NEWS EVERYONE WILL LOVE IT!!!!!!!!!!!!!!!!!!!!!!!!!I wILL TELL EVERYONE IN YOUTUBE THEREES ALMOST 2K PEOPLE THERE :D ur the besttttttttttttttttttttttttttttttttttttttttttttttttttttttttt

**Comment by XREALM-YT** [comment]
> Not now, but it will be available in the settings menu. We plan to add this feature by the end of the year. 

How can i use mods or arent there? Or we cant do that @MoNTE48

**Comment by MoNTE48** [comment]
MultiCraft does not support mods at the moment. I cannot say when they will be supported or whether they will be supported at all.

**Comment by XREALM-YT** [comment]
> MultiCraft does not support mods at the moment. I cannot say when they will be supported or whether they will be supported at all.

Ok @MoNTE48 i think mods will break the game lol we shouldnt have that

**Comment by OPStellar** [comment]
There's a way to enable TNT and PVP now.
In the console, use the following commands…
for PVP: `/area_pvp <ID>`
for TNT: `/settings`
![image](https://user-images.githubusercontent.com/49218413/158095943-1bfaed66-a2cf-4bb5-886c-a35b65be905d.png)
then change the settings as you desire

**Comment by Oussamaragdouz** [comment]
مرحبا، اللعبة تنقصها اللغة العربية!!
متى سيتم إضافتها؟؟
