### ISSUE TITLE
Wtfreak

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#28]
I banned someone named yourty who griefed my server :/ when i put/ban yourty it banned me too why

**Comment by MoNTE48** [comment]
Friend, I'll tell you one last time. This repository was created for game development. We don't deal with servers. We do not manage hosting. We don't know what happened to you. We're just coding. Please do not waste time on these questions. Thanks.

**Comment by XREALM-YT** [comment]
> Friend, I'll tell you one last time. This repository was created for game development. We don't deal with servers. We do not manage hosting. We don't know what happened to you. We're just coding. Please do not waste time on these questions. Thanks.

I only report bugs right no more stuff like this i get it now
