### ISSUE TITLE
X-RAY

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#3]
Hello I’m XREALM the multicraft supporter :D anyway I came to talk about Players CHEATING! they use a X-ray glitch to see through caves and collect DIAMONDS IN A INSTANT :| ok here’s how they do it... This issue happens when you go to 3rd person view and cover the sides and top bottom of yourself with any block then you go to 3rd person you can see caves and underground bases... Incase you did it get what I’m saying watch this...

https://youtu.be/1N9TmUtbTyg There’s some more bugs there too to fix up :) 
And thanks for making the WOLRD BETTER 👍 love ❤️ MultiCraft:)

**Comment by XREALM-YT** [comment]
How can you disable PvP and damage on a server? 
Pls reply :)

**Comment by MoNTE48** [comment]
Impossible to fix right now. Limitations of the game engine. 😕

**Comment by XREALM-YT** [comment]
😢 That’s sad I can tell them to pls stop using that bug 🐜 

Wait a sec. how can a game get fixed? If I learn coding and programming maybe I can do stuff? :| I really worry of this game :) :D
