### ISSUE TITLE
No warned for cursing ? 

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#37]
People say um bad words they dont be warned for cursing also on both multicraft survival and creative servers pls add moderators or something pls 🥺 people rob in survival server and rob pls make someone supervize 
I know some greifers who can PLACE WATER EVEN IF ITS A HIGH PLACE! :| ! ... Jessica15 does this she kills everyone.PLS ADD A MODERATOR pls to checkout the server in secret pls i beg you boss @MoNTE48 i like calling you boss ;) but anyway pls do something also block the spanish bad words idk what they say but i also see the S word pls block it too

**Comment by MoNTE48** [comment]
We do not have the resources to maintain the servers. There are no moderators and no plans.
Blocking bad words requires curse words list. Most of Russian and English bad words are currently in black list.

**Comment by XREALM-YT** [comment]
> We do not have the resources to maintain the servers. There are no moderators and no plans.
> Blocking bad words requires curse words list. Most of Russian and English bad words are currently in black list.

.youll probably not reply after what i say :/ i want to be moderator or a spectator i can just have privs interact and shout but look at the chat. If you dont like my idea its ok:) my friend . And just now how in the world do we still have water source blocks that work? O_O?
