### ISSUE TITLE
Moon walk

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#44]
Is it normal for The mobs to walk backwards? I sometimes see they do

**Comment by MoNTE48** [comment]
Well, that's not okay. But I've never seen it.
---
Q: How does the Issue title relate to the issue? Please use the correct titles. Otherwise, your issues will be deleted.

**Comment by XREALM-YT** [comment]
> Well, that's not okay. But I've never seen it.
> ---
> Q: How does the Issue title relate to the issue? Please use the correct titles. Otherwise, your issues will be deleted.

Ok
