### ISSUE TITLE
New titlescreen

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#46]
I wish we had a title like this
![20201103_211325.jpg](https://user-images.githubusercontent.com/73010605/98065549-6eb0de00-1e1a-11eb-91c3-f414a761eb6b.jpg) or is it bad

**Comment by MoNTE48** [comment]
Rather like a game whose name I can't pronounce. And this is terribly inconvenient (as for me).
Our team is working on the best menu concept.

**Comment by XREALM-YT** [comment]
> Rather like a game whose name I can't pronounce. And this is terribly inconvenient (as for me).
> Our team is working on the best menu concept.

Yeah :) im not gonna mention that other game that has a title like this one cuz i do not want to advertize it. @MoNTE48 can i edit a photo and send em here to show you and make em differenter?

**Comment by XREALM-YT** [comment]
> Rather like a game whose name I can't pronounce. And this is terribly inconvenient (as for me).
> Our team is working on the best menu concept.
@MoNTE48 
I do not like ********* that game ugh i want this one to WIN and it is working. I want multicraft #1 so i keep Growing it on youtube people do check it out! I LOVE MULTICRAFT FOREVER! and i havent played other games for 2 years rn cuz im always enjoying this one
