### ISSUE TITLE
Is "Fast" Available? And how to use?

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#47]
![Screenshot_20201103-203355_Gallery.jpg](https://user-images.githubusercontent.com/73010605/98162936-a7e35f80-1ea7-11eb-9770-04384c677ce2.jpg)

If we cant use fast can you add it? And also make blocks break faster in creative pls reply soon

**Comment by MoNTE48** [comment]
No, fast is not available in multiplayer and singleplayer right now.
We'll take a look at speeding up the block break time in a creative mode in future updates.

**Comment by XREALM-YT** [comment]
> No, fast is not available in multiplayer and singleplayer right now.
> We'll take a look at speeding up the block break time in a creative mode in future updates.

Thank you
