### ISSUE TITLE
Too much liquid is bad right?

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#48]
What are the Y coords where we cant place water in multiplayer?

**Comment by MoNTE48** [comment]
https://github.com/MultiCraft/MultiCraft_game/blob/master/files/bucket/init.lua#L106-L122

**Comment by XREALM-YT** [comment]
> https://github.com/MultiCraft/MultiCraft_game/blob/master/files/bucket/init.lua#L106-L122

idk what all this means

**Comment by XREALM-YT** [comment]
> https://github.com/MultiCraft/MultiCraft_game/blob/master/files/bucket/init.lua#L106-L122

Im asking cuz so many griefers in the servers :/ doing it free

**Comment by MoNTE48** [comment]
Lava is not higher than +8. Water is not higher than +64.
I know the bug they are using. I'll fix it when I have free time.

**Comment by XREALM-YT** [comment]
> Lava is not higher than +8. Water is not higher than +64.
> I know the bug they are using. I'll fix it when I have free time.

YES IVE BEEN SAVED! BY @MoNTE48 !

**Comment by githubXREALM** [comment]
> Lava is not higher than +8. Water is not higher than +64.
> I know the bug they are using. I'll fix it when I have free time.

Thank you @MoNTE48

**Comment by githubXREALM** [comment]
> Lava is not higher than +8. Water is not higher than +64.
> I know the bug they are using. I'll fix it when I have free time.

@MoNTE48 they crouch and place it or using water_source too tho

**Comment by githubXREALM** [comment]
> Lava is not higher than +8. Water is not higher than +64.
> I know the bug they are using. I'll fix it when I have free time.

Thanks again

**Comment by githubXREALM** [comment]
> > Lava is not higher than +8. Water is not higher than +64.
> > I know the bug they are using. I'll fix it when I have free time.
> 
> YES IVE BEEN SAVED! BY @MoNTE48 !

@XREALM-YT :(
