### ISSUE TITLE
New title screen #2 last try of me

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#49]
![20201104_195835.jpg](https://user-images.githubusercontent.com/73010605/98189430-949db780-1eda-11eb-96f1-eebc779e0ca9.jpg)
![20201104_200955.jpg](https://user-images.githubusercontent.com/73010605/98189435-98c9d500-1eda-11eb-9abf-86a67ab4a894.jpg)
![20201104_201047.jpg](https://user-images.githubusercontent.com/73010605/98189443-9d8e8900-1eda-11eb-8f95-0a135e5bba6a.jpg)
![20201104_201112.jpg](https://user-images.githubusercontent.com/73010605/98189460-a1baa680-1eda-11eb-93ea-fda9d5d6dcad.jpg)
Did you like them? Or atleast its an idea i love designing

**Comment by githubXREALM** [comment]
> ![20201104_195835.jpg](https://user-images.githubusercontent.com/73010605/98189430-949db780-1eda-11eb-96f1-eebc779e0ca9.jpg)
> ![20201104_200955.jpg](https://user-images.githubusercontent.com/73010605/98189435-98c9d500-1eda-11eb-9abf-86a67ab4a894.jpg)
> ![20201104_201047.jpg](https://user-images.githubusercontent.com/73010605/98189443-9d8e8900-1eda-11eb-8f95-0a135e5bba6a.jpg)
> ![20201104_201112.jpg](https://user-images.githubusercontent.com/73010605/98189460-a1baa680-1eda-11eb-93ea-fda9d5d6dcad.jpg)
> Did you like them? Or atleast its an idea i love designing 

"/

**Comment by MoNTE48** [comment]
Why is this needed? Because it will repeat the MainMenu style of another game.
We are not interested in this.
