### ISSUE TITLE
Ads disturb the game expirience

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#50]
I cant enjoy multicraft like i did before. The ads keep coming a lot and glitch my phone 
![Screenshot_20201105-203852_MultiCraft.jpg](https://user-images.githubusercontent.com/73010605/98319977-8d90ab00-1fa7-11eb-90bf-e59837006862.jpg)

![Screenshot_20201105-200117_MultiCraft.jpg](https://user-images.githubusercontent.com/73010605/98319986-941f2280-1fa7-11eb-8c87-f9dfa07ddb1b.jpg)
It glitches the joystick too tho

**Comment by MoNTE48** [comment]
Joystick issue will be (probably) fixed in the next update.

**Comment by XREALM-MultiCraft** [comment]
Good :D
