### ISSUE TITLE
Bluestone

### ISSUE THREAD

**Issue by Limitlessplayz** [MultiCraft/MultiCraft_game#52]
Please upgrade bluestone and improve the game! I love the game and I want updates to at least make something interesting. ( and also can you... got a lot of questions)

**Comment by githubXREALM** [comment]
> Please upgrade bluestone and improve the game! I love the game and I want updates to at least make something interesting. ( and also can you... got a lot of questions)

I want too

**Comment by githubXREALM** [comment]
> Please upgrade bluestone and improve the game! I love the game and I want updates to at least make something interesting. ( and also can you... got a lot of questions)

Wait up here is to report bugs

**Comment by githubXREALM** [comment]
> Please upgrade bluestone and improve the game! I love the game and I want updates to at least make something interesting. ( and also can you... got a lot of questions)

I also want to make things Interesting

**Comment by MoNTE48** [comment]
@githubXREALM If you continue to spam, you will be blocked for life. This is not a chat.
