### ISSUE TITLE
Add a "Cheese recipe on workbench

### ISSUE THREAD

**Issue by XREALM-MultiCraft** [MultiCraft/MultiCraft_game#54]
Hello today i was searching on the workbench cheese recipes. I found cheese blocks and cheese but one thing i don't see..
How to make cheese. i see you make cheese with cheeseblock but i cant craft cheese like new cheese. Can you add a cheese recipe? I have made one heres a image an by the way also wondering how to make slimeblocks.
![Polish_20201202_150213733](https://user-images.githubusercontent.com/74271666/100933245-af038a80-34b2-11eb-8eec-d9d154fa6f58.jpg)
To get cheese milk the cow must eat dry grass.......i bug report ask things and give ideas 1 time a month ok to not spam :/\. Lemme know what do you think of the recepie or if theres already a way to make new cheese .heres a example-> cow eats dry grass then if a player gets milk from it. The cow will give "Cheese Milk" you can heat it up in furnace for cheese UwU

**Comment by XREALM-MultiCraft** [comment]
![Polish_20201202_134915577](https://user-images.githubusercontent.com/74271666/100933919-a3fd2a00-34b3-11eb-8173-a5a1d6c09f6f.png)
Cheese milk bucket

**Comment by XREALM-MultiCraft** [comment]
@MoNTE48 one last thing for the month what is level up tools for? And whats the maximum lvl?

**Comment by MoNTE48** [comment]
What is cheese milk? Have you ever been to a farm in real life?
The cheese is crafted by cooking milk in furnace.

**Comment by MoNTE48** [comment]
> @MoNTE48 one last thing for the month what is level up tools for? And whats the maximum lvl?

https://github.com/MultiCraft/MultiCraft_game/blob/master/files/toolranks/init.lua#L15

**Comment by XREALM-MultiCraft** [comment]
> What is cheese milk? Have you ever been to a farm in real life?
> The cheese is crafted by cooking milk in furnace.

Oh thank you never knew that
