### ISSUE TITLE
Can’t connect to server

### ISSUE THREAD

**Issue by bhawks2** [MultiCraft/MultiCraft_game#57]
Hello, I am having an issue where when I connect to my single player world1 it keeps telling me cant connect to server. I can connect to all the other worlds except world 1. How do I get this back?

**Comment by MoNTE48** [comment]
Hello. Sorry for that. I really hope the problem has been solved for you?
Tell me, if not.

**Comment by MoNTE48** [comment]
If there is no response during these days, I hope the problem has been resolved and close this.
