### ISSUE TITLE
Micro_slabs nodes has collision issue

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#6]
Sometimes I go to a bridge I built in the game and I go through it 
It happens on micro_slabs & stairs when I just walk on it and their on the air

**Comment by githubXREALM** [comment]
> Sometimes I go to a bridge I built in the game and I go through it 
> It happens on micro_slabs & stairs when I just walk on it and their on the air 

It still is like that

**Comment by MoNTE48** [comment]
I have heard about this bug. It was probably fixed in Minetest Engine 5.1 or so.
We are planning an upgrade to the newest version of Engine soon.

**Comment by XREALM-MultiCraft** [comment]
Good big thumbs up 👍👍👍 i will be in YouTube making videos ima get to work :)

**Comment by JBTHECRAFTER** [comment]
Hi xrealm ;-;
