### ISSUE TITLE
Keeps crashing and not letting me and my friends in my server or their servers

### ISSUE THREAD

**Issue by Multicraftbuilder2007** [MultiCraft/MultiCraft_game#60]

**Comment by Matt1559** [comment]
I'm having the same problem

**Comment by MoNTE48** [comment]
Hello @Multicraftbuilder2007 and @Matt1559 . Sorry for that. I really hope the problem has been solved for you? Tell us your Invite code if not.

**Comment by MoNTE48** [comment]
If there is no response during these days, I hope the problem has been resolved and close this.
