### ISSUE TITLE
Bluestone

### ISSUE THREAD

**Issue by ginggingthepharmacist** [MultiCraft/MultiCraft_game#65]
Bluestone had an important mechanic where it could connect up blocks. Now, it only works when the bluestone is level to the bluestone source. This bug not only prevents flying machines from working but also breaks a lot of bluestone builds. Please revert the bluestone mechanic changes back to the previous update.

**Comment by MoNTE48** [comment]
Hello. Consider a demonstration of your issue (screenshots, videos).
Bluestone's behavior change was deliberate to increase the realism of the game.

**Comment by ginggingthepharmacist** [comment]
Could you please patch it back so this can work? I really need this to be
fixed, otherwise it breaks some of my builds. Also, I was kinda hoping for
flying machines to be added in Multicraft.

**Comment by MoNTE48** [comment]
Without demonstrating the problem, I really can't help you. As I said, any videos or screenshots would be helpful.

**Comment by noahplayer** [comment]
Yeah the bluestones rails don’t work either

**Comment by MoNTE48** [comment]
@noahplayer, I just checked and everything works for me.
I will leave this open for a while, but if the requested information is not provided, the Issue will be closed.
