### ISSUE TITLE
A problem and an update

### ISSUE THREAD

**Issue by noahplayer** [MultiCraft/MultiCraft_game#67]
1. I would really like enchantments even if they’re basic
2. Bluestone rails don’t work
3. The bow animations are weird

**Comment by MoNTE48** [comment]
It is necessary to clarify update version and on which platform we are talking about.

**Comment by noahplayer** [comment]
Version 1.15.7

**Comment by noahplayer** [comment]
And on iOS

**Comment by OwOBot27** [comment]
Hmm i too wait enchants
