### ISSUE TITLE
i get this error and just fall

### ISSUE THREAD

**Issue by jcq333** [MultiCraft/MultiCraft_game#69]
![Screenshot from 2021-05-24 22-38-00](https://user-images.githubusercontent.com/81051943/119436219-5f737e00-bce1-11eb-98d1-8a881e055bc9.png)
my specs
![Screenshot from 2021-05-24 22-42-26](https://user-images.githubusercontent.com/81051943/119436217-5f737e00-bce1-11eb-818f-bad4800c9ab7.png)

**Comment by MoNTE48** [comment]
MultiCraft game is not compatiable with MultiCraft 2.0.0 Engine yet.

**Comment by jcq333** [comment]
when will it?

**Comment by MoNTE48** [comment]
We do not have any specific deadlines and continue to use the `MultiCraft-legacy` engine for official clients on Android and iOS.

**Comment by Festus1965** [comment]
hmm minetest-game 5.2.0 is not complaining at MultiCraft2 95e1e26 (31.08.) at me
starting as under mt-5.2.0, same config
just another 3 mods are ... from a lot

**Comment by MoNTE48** [comment]
@Festus1965, we have been updated to Minetest 5.4.1 and are more stable than ever.
Feel free to use the latest Minetest_game and enjoy the most right "Minetestserver" without compatibility issues 😉

**Comment by rudzik8** [comment]
so, multicraft_game is still working ONLY with the legacy, 0.4.x-based engine?
like, is it THAT hard to port game for new engine? 
and where's info about this in README?

i wanted to play multicraft in singleplayer on my PC, but there aren't any legacy multicraft builds as i can see, sadly
multicraft2 builds (artifacts) are downloable but multicraft_game is unsupported
and yes, i'm too lazy to build it and there aren't any instructions how to build for legacy engine in README

i can play minetest_game from my regular minetest client, without any bugs and texture style difference. but i want to play multicraft game, not minetest game.

please, can you set up automated builds for legacy engine? or finally make multicraft_game work with multicraft2?
