### ISSUE TITLE
Hosted server recovery 

### ISSUE THREAD

**Issue by XREALM-YT** [MultiCraft/MultiCraft_game#7]
My issue I can’t recover my hosted server from another Device :( it dosent work 
Pls add recover server for other devices with I’d and password so I won’t lose all my stuff
Pls pls and one Question. Are you the Admin of the MultiCraft survival and creative server?

**Comment by MoNTE48** [comment]
We are already working on this and plan to add it in the future. It has nothing to do with this repository

**Comment by XREALM-YT** [comment]
> We are already working on this and plan to add it in the future. It has nothing to do with this repository

Wait I’m at repository? O-O how did I end up here :| I send issues at the issue button on top?

**Comment by XREALM-YT** [comment]
> We are already working on this and plan to add it in the future. It has nothing to do with this repository

Ok thanks! Multi Maksim :) that kinda rhymes 😁
