### ISSUE TITLE
Loading Issue

### ISSUE THREAD

**Issue by agaulter** [MultiCraft/MultiCraft_game#82]
Just downloaded this game last night on my new Mac. It worked perfectly fine but, this morning when I tried opening it I kept getting a completely black screen and the game never loads. Any suggestions on how to fix this?? Thanks.

**Comment by MoNTE48** [comment]
Hello. Try to open this path in **Finder** and remove **multicraft.conf** file.
How to open: Go -> Go to Location -> Paste this path and change `YOUR_USER_NAME` to your user name 🙂
`/Users/YOUR_USER_NAME/Library/Containers/mobi.MultiCraft/Data/Library/Application Support/MultiCraft`
