### ISSUE TITLE
Can’t turn

### ISSUE THREAD

**Issue by Springbokza** [MultiCraft/MultiCraft_game#85]
Updated to Version 1.21.0 and can no longer turn player body around.
Using iPhone 6s

**Comment by MoNTE48** [comment]
The issue has not been confirmed. Please attach a video demonstrating the problem.

**Comment by Springbokza** [comment]
Video attached

Uploading 20220225_190437.mp4…

**Comment by Springbokza** [comment]
Uploading 20220225_192352.mp4…

**Comment by MoNTE48** [comment]
Upload video on YouTube or any video hosting, please

**Comment by Springbokza** [comment]
It is already on Max.
![Uploading 16458702444776161767945921846177.jpg…]()

**Comment by MoNTE48** [comment]
Just try changing the setting to a ~50% for example. And don't press "Comment" button here until the image has finished loading.
