### ISSUE TITLE
Support MultiCraft 2.0 (new engine)

### ISSUE THREAD

**Issue by rudzik8** [MultiCraft/MultiCraft_game#88]
As I can see, MultiCraft legacy is already abandoned (see [`ee75dd1`](https://github.com/MultiCraft/MultiCraft-legacy/commit/ee75dd125b32788f41fe18c7fcb8c1b60098eef6)), and the next release will be based on 2.0. It's very nice and means that more people will be able to play MLC!

So, if MLC 2.0 will support MultiCraft_game, it will mean that:
1. PC players will be able to play MultiCraft in singleplayer as well (btw, are normal PC releases coming soon? if not, we still have artifacts), so no more just crowds of 5yo mobile players on MLC-only servers (which are blocked by official Minetest serverlist), with time there will be more normal PC players, no more need to find MultiCraft server IP+ports and entering them by hand from Minetest to join
2. Related to 1, more PC players = more modders, normal YouTubers = more popularity (currently, all the populatiry is just from mobile users who tried to download "free minecraft" from Google Play). More modders = more people that can expand game and fix bugs (yes, we have MT modders but they aren't so interested in MultiCraft)
3. Porting mods will be **a lot** easier, cause now you won't need to backport mods or find older versions of them for MT-0.4.x (or even writing from scratch). Good for servers I guess

@MoNTE48  Maybe I'm wrong in some parts, just issue to remind you and other MLC devs about this (offtopic, but is **MLC** for **M**u**l**ti**C**raft is ok? Like, we use **MT** for **M**ine**t**est, **MCL** for **M**ine**Cl**one, and overriding **MC** for Minecraft with **MC** for **M**ulti**C**raft would be weird)

**Related:** #69

**Comment by MoNTE48** [comment]
Hi! MultiCraft development is a closed process with Open Source parts being published under the license.
I don't think the company that owns the rights and the trademark MultiCraft has any interest in PC or unofficial mods.
In any case, thanks for your interest.
(Unofficially we call our game MC2. The official name, according to the registered trademark is MultiCraft).
