### ISSUE TITLE
MultiCraft Android app is in violation of LGPL license of included mods

### ISSUE THREAD

**Issue by MrRar** [MultiCraft/MultiCraft_game#97]
3D Armor is licensed under GNU Lesser General Public License 3+: https://www.gnu.org/licenses/lgpl-3.0.en.html

Here is a quote:
```
   d) Do one of the following:

       0) Convey the Minimal Corresponding Source under the terms of this
       License, and the Corresponding Application Code in a form
       suitable for, and under terms that permit, the user to
       recombine or relink the Application with a modified version of
       the Linked Version to produce a modified Combined Work, in the
       manner specified by section 6 of the GNU GPL for conveying
       Corresponding Source.

       1) Use a suitable shared library mechanism for linking with the
       Library.  A suitable mechanism is one that (a) uses at run time
       a copy of the Library already present on the user's computer
       system, and (b) will operate properly with a modified version
       of the Library that is interface-compatible with the Linked
       Version.
```
The MultiCraft game is distributed in LuaJIT byte code. There is no way to replace the version of 3D Armor included with MultiCraft with a newer version of 3D Armor.

Please release all of MultiCraft as open source software. The inventory mod is missing for example.

**Comment by MoNTE48** [comment]
Hi. As far as I know, MultiCraft no longer distributes any games. All games are downloaded by the player from the Content DB or played via server side singleplayer mode. Both are fully compliant with the GNU LGPL license.

I recommend that you consult a qualified lawyer for advice.

**Comment by MrRar** [comment]
> Hi. As far as I know, MultiCraft no longer distributes any games. All games are downloaded by the player from the Content DB or played via server side singleplayer mode. Both are fully compliant with the GNU LGPL license.
> 
> I recommend that you consult a qualified lawyer for advice.

The MultiCraft Android app most certainly comes with the MultiCraft game. To make sure we are talking about the same thing, here it is: https://play.google.com/store/apps/details?id=com.multicraft.game

The Windows MultiCraft however comes with no MultiCraft Game but I am not talking about that.

Why don't you just release the full MultiCraft Game as open source? I mean this repo is useless with out the missing parts.

**Comment by MoNTE48** [comment]
@MrRar, if you are the author (or designee) of any supposedly used source code or media, I suggest you contact the game's publishers directly.
Otherwise, I can't help and close this Issue as invalid.

**Comment by MrRar** [comment]
@MoNTE48, I thought you were the publisher of MultiCraft. Who is if not you? I thought this was your gig?

**Comment by mckaygerhard** [comment]
@MrRar  when the same people you cited are the same people that work with  him, i guess there's no way to give some justice cos there are money involved.. sadly, event if this comment its erased.. the notification will raise.. for sure
